using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SpreadCommander.Common.Script.Chart
{
    public enum ChartViewType
    {
        Bar                        = 0,
        StackedBar                 = 1,
        FullStackedBar             = 2,
        SideBySideStackedBar       = 3,
        SideBySideFullStackedBar   = 4,
        Pie                        = 5,
        Doughnut                   = 6,
        NestedDoughnut             = 7,
        Funnel                     = 8,
        Point                      = 9,
        Bubble                     = 10,
        Line                       = 11,
        StackedLine                = 12,
        FullStackedLine            = 13,
        StepLine                   = 14,
        Spline                     = 15,
        ScatterLine                = 16,
        SwiftPlot                  = 17,
        Area                       = 18,
        StepArea                   = 19,
        SplineArea                 = 20,
        StackedArea                = 21,
        StackedStepArea            = 22,
        StackedSplineArea          = 23,
        FullStackedArea            = 24,
        FullStackedSplineArea      = 25,
        FullStackedStepArea        = 26,
        RangeArea                  = 27,
        Stock                      = 28,
        CandleStick                = 29,
        SideBySideRangeBar         = 30,
        RangeBar                   = 31,
        SideBySideGantt            = 32,
        Gantt                      = 33,
        PolarPoint                 = 34,
        PolarLine                  = 35,
        ScatterPolarLine           = 36,
        PolarArea                  = 37,
        PolarRangeArea             = 38,
        RadarPoint                 = 39,
        RadarLine                  = 40,
        ScatterRadarLine           = 41,
        RadarArea                  = 42,
        RadarRangeArea             = 43,
        Bar3D                      = 44,
        StackedBar3D               = 45,
        FullStackedBar3D           = 46,
        ManhattanBar               = 47,
        SideBySideStackedBar3D     = 48,
        SideBySideFullStackedBar3D = 49,
        Pie3D                      = 50,
        Doughnut3D                 = 51,
        Funnel3D                   = 52,
        Line3D                     = 53,
        StackedLine3D              = 54,
        FullStackedLine3D          = 55,
        StepLine3D                 = 56,
        Area3D                     = 57,
        StackedArea3D              = 58,
        FullStackedArea3D          = 59,
        StepArea3D                 = 60,
        Spline3D                   = 61,
        SplineArea3D               = 62,
        StackedSplineArea3D        = 63,
        FullStackedSplineArea3D    = 64,
        RangeArea3D                = 65,
        BoxPlot                    = 66,
        Waterfall                  = 67,
        SwiftPoint                 = 68
    }
}
